pet_store/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets
  root 'pets#index'
end

pet_store/app/models/pet.rb
class Pet < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :description, length: {minimum: 10}
end

pet_store/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links
end

pet_store/app/controllers/pets_controller.rb
private
  def pet_params
    params.require(:pet).permit(:name, :age, :description)
  end

class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[ :id])
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to @pet
    else
      render 'new'
    end
  end

  def update
    @pet = Pet.find(params[:id])

    if @pet.update(pet_params)
      redirect_to @pet
    else 
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    
    redirect_to pets_path
  end
end

pet_store/app/helpers/pets_helper.rb
module PetsHelper
end

pet_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

pet_store/app/views/pets/_form.html.erb
<%= form_with model: @pet, data: { turbo: false }, local: true do |form| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

pet_store/app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= render 'form' %>

pet_store/app/views/pets/index.html.erb
<table>
  <tr>
    <th colspan="5"></th>
  </tr>
  <%= link_to 'New pet', new_pet_path %>
  <% @pets.each do |p| %>
    <tr>
        <td><%= link_to p.name, pet_path(p)  %></td>
        <td><%= link_to 'Edit', edit_pet_path(p) %></td>
        <td><%= button_to 'Remove', pet_path(p), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

pet_store/app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= render 'form' %>

pet_store/app/views/pets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<%= link_to 'Home', pets_path %>
<%= link_to 'Edit', edit_pet_path %>
<%= button_to 'Remove', @pet, method: :delete, data: { confirm: 'Are you sure?' } %>