linkShare2/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :links do
    member do
      put 'like' => 'links#like'
      put 'dislike' => 'links#dislike'
    end
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'links#index'
end

linkShare2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

linkShare2/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
end

linkShare2/app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user
    acts_as_votable
    has_many :comments
    validates :title, presence: true
end

linkShare2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links
  acts_as_voter
end

linkShare2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

linkShare2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :link_id, :user_id)
    end
end

linkShare2/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end
  
  def like
    @link = Link.find(params[:id])
    if (params[:format]) == 'like'
      @link.liked_by current_user
    elsif params[:format] == 'unlike'
      @link.unliked_by current_user
    end
    redirect_back fallback_location: root_path
  end

  def dislike
    @link = Link.find(params[:id])
    if params[:format] == 'dislike'
      @link.disliked_by current_user
    elsif params[:format] == 'undislike'
      @link.undisliked_by current_user
    end
    redirect_back fallback_location: root_path
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

linkShare2/app/helpers/application_helper.rb
module ApplicationHelper
end

linkShare2/app/helpers/comments_helper.rb
module CommentsHelper
end

linkShare2/app/helpers/links_helper.rb
module LinksHelper
end

linkShare2/app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= comment.link_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

</div>

linkShare2/app/views/comments/_form.html.erb
<%= form_with(model: [@link, @link.comments.build ]) do |form| %>
  <p>
    <br>
    <%= form.text_area :body%>
  </p>
  <p>
    <%= form.submit "Add Comment" %>
  </p>
<% end %>

linkShare2/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

linkShare2/app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

linkShare2/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

linkShare2/app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

linkShare2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>

  <% if user_signed_in? %>
    <ul>
      <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
      <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %></li>
    </ul>
   <% else %>
    <ul>
     <li><%= link_to 'Sign up', new_user_registration_path%></li>
     <li><%= link_to 'Sign in', new_user_session_path %></li>
    </ul>
  <% end %>

    <%= yield %>
  </body>
</html>

linkShare2/app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

linkShare2/app/views/links/_link.html.erb
<%
=begin%>
 <div id="<%= dom_id link %>">
  <p>
    <strong>Title:</strong>
    <%= link.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link.url %>
  </p>

</div> 
<%
=end%>

linkShare2/app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

linkShare2/app/views/links/index.html.erb
<h1>Links</h1>
<% @links.each do |link| %>
  <div>
    <h2>
        <%= link_to link.title, link %><br>
        <small> Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.email %></small>
    </h2>

  <div>
    <a href="<%= link.url %>">Go to Link</a>
    <% if user_signed_in? %>
      <% if current_user.liked? link %>
            <%= link_to 'unlike', like_link_path(link, 'unlike'), method: :put, remote: :true %>
          <% else %>
            <%= link_to 'like', like_link_path(link, 'like'), method: :put, remote: :true %>
          <% end %>
        <%= link.get_upvotes.size %>

        <% if current_user.disliked? link %>
            <%= link_to 'undislike', dislike_link_path(link, 'undislike'), method: :put, remote: :true %>
          <% else %>
            <%= link_to 'dislike', dislike_link_path(link, 'dislike'), method: :put, remote: :true %>
          <% end %>
        <%= link.get_upvotes.size %>
    <% end %>
    
  </div>
  </div>
<% end %>

<br>

<%= link_to 'New Link', new_link_path %>

linkShare2/app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

linkShare2/app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<h2> Comment </h2>
<% @link.comments.each do |comment| %>
<p><%= comment.user.email %> Commented: <%= comment.body %></p>
<% end %>

<%= render 'comments/form' %>

<% if @link.user == current_user %>
  <%= link_to 'Edit', edit_link_path(@link) %>
  <%= button_to 'Delete', @link, method: :delete  %>
<% end %>

<%= link_to 'Back', links_path %>